---
title: "Lijia Yu's resume"
author: Lijia Yu
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css:
      - override.css
      - resume
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
# uncomment this line to produce HTML and PDF in RStudio:
knit: pagedown::chrome_print
---

Aside
================================================================================

CONTACT INFO {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-github"></i> [github.com/Jumbong](https://github.com/Jumbong)
- <i class="fa fa-phone"></i> +33 (0)753865698
- <i class="fa-brands fa-linkedin"></i> [linkedin.com/Jumbong](www.linkedin.com/in/junior-jumbong-258330211)
<i class="fa-solid fa-location-dot"></i>  Rennes(FRANCE)



LANGUAGES {#contact}
--------------------------------------------------------------------------------

- Français : Langue maternelle
- Anglais :  Niveau B2



OUTILS D'ANALYSE  {#skills}
--------------------------------------------------------------------------------

- Expérimenté en analyse statistique, en modèles d'apprentissage statistique et en méthodes d'optimisation.

- Compétent en Python (Scikit-Learn), R (Tidyverse), SQL, SAS, VBA, Bash, LaTeX, et C++ (niveau de base).



LOISIRS {#skills}
--------------------------------------------------------------------------------

- A voyagé dans 4 pays
- Passionné par la participation à des activités sportives telles que le football, la course à pied, le handball et la boxe.

----------------------------------------------------------------------------------

<footer>
- Ce CV a été réalisé à l'aide du package R [**pagedown**](https://github.com/rstudio/pagedown).
</footer>


Main
================================================================================

Jumbong Junior {#title}
--------------------------------------------------------------------------------

### Recherche un stage de fin d'études de 6 mois en Ingénierie Financière


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### ECOLE NATIONALE DE LA STATIStiQUE ET DE L'ANALYSE DE L'INFORMATION (ENSAI)

GESTION DES RISQUES

Rennes, France

2022 - 2024

Master d'une école d'ingénieurs axée sur des cours statistiques (Apprentissage Automatique, séries temporelles) et programmation (Python, R, SQL). Spécialisation en dernière année en Gestion des Risques et Ingénierie Financière, couvrant des sujets tels que les risques bancaires et les méthodes de scoring

### ECOLE NATIONALE DE LA STATISTIQUE ET DE L'ANALySE ECONOMIQUE (ENSAE)

INGENIEUR EN STATISTIQUE ET EN ECONOMIE (ISE)

Dakar, Sénégal

2020 - 2021

Finalisation avec succès de la première année d'un cursus de Master en Ingénierie Économique, incluant des modules spécialisés en Économétrie, Statistiques, Programmation, Macroéconomie et Théorie des Jeux.

### UNIVERSITE DE YAOUNDE I

MATHEMATIQUES

Yaoundé , Cameroun

2017 - 2020

Obtention d'une Licence en mathématiques, incluant des cours tels que l'Analyse Numérique (utilisant Python et MATLAB), Statistiques, Probabilités et Algèbre.

Experience Professionnel {data-icon=suitcase}
--------------------------------------------------------------------------------

### ANALYSTE DES DONNEES | HSBC

PROJET DE FIN D'ETUDES

ENSAI, Rennes

Nov 2023 - en cours


- Analyse de la sensibilité des données financières, telles que les écarts de crédit, par rapport à des indicateurs climatiques comme les émissions de carbone.
- Étude de la répartition des variables climatiques au sein des dettes souveraines.
- Analyse potentielle basée sur différents scénarios climatiques proposés par le NGFS (Network for Greening the Financial Services).

### SERIES TEMPORELLES

PREVISION DE LA CONSOMMATION D'ENERGIE

ENSAI, Rennes

Nov 2023 - Dec 2023

- Analyse des données historiques de consommation d'énergie et élaboration d'un modèle de prévision pour la demande énergétique future.

### ASSISTANT CHERCHEUR

[INRIA](https://www.inria.fr/fr/sistm)  : EQUIPE SISTM

Bordeaux , France

Août 2023 - Sep 2023

- Réalisation des recherches en biologie computationnelle pour comprendre la réponse immunitaire au vaccin contre Ebola.
- Découverte des impacts significatifs de l'âge, du genre, du pays et des variables de laboratoire sur la variabilité de la réponse immunitaire.

### ASSISTANT CHERCHEUR

HÔPITAL EUROPEEN GEORGES POMPIDOU

Paris, France

Fev 2023 -  Sep 2023

- Réalisation des travaux de recherche en biologie computationnelle pour examiner les effets de la fuite capillaire sur la de mortalité, en utilisant des techniques de Régression Logistique et de Régression à Effets Mixtes Généralisés.
- Gestion et analyse de données via la base de données [MIMIC-IV](https://physionet.org/content/mimiciv/0.4/), en exploitant des requêtes SQL pour extraire et traiter l'information pertinente.



```{js move_disclaim, echo=FALSE}
(function() {
    var pages 
    var timer = 0;
    var changeDC = setInterval(function() {
        pages = document.querySelectorAll('.pagedjs_page');
        if(pages.length !== 2 && timer <= 5000) {
            timer += 200;
            return;
        }
        if(pages.length !== 2 && timer > 5000) return clearInterval(changeDC);
        var firstPage = pages[0];
        var lastePage = pages[pages.length - 1];
        var aside = firstPage.querySelector('#aside');
        var asideClone = aside.cloneNode();
        asideClone.id = "aside_last";
        var disclaim = document.querySelector('#disclaimer');
        asideClone.appendChild(disclaim);
        lastePage.querySelector('.pagedjs_page_content > div').appendChild(asideClone);
        clearInterval(changeDC);
    }, 200);
})()
```

