---
title: "Lijia Yu's resume"
author: Lijia Yu
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    css:
      - override.css
      - resume
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: false
# uncomment this line to produce HTML and PDF in RStudio:
knit: pagedown::chrome_print
---

Aside
================================================================================

CONTACT INFO {#contact}
--------------------------------------------------------------------------------

- <i class="fa fa-github"></i> [github.com/Jumbong](https://github.com/Jumbong)
- <i class="fa fa-phone"></i> +33 (0)753865698
- <i class="fa-brands fa-linkedin"></i> [linkedin.com/Jumbong](www.linkedin.com/in/junior-jumbong-258330211)
<i class="fa-solid fa-location-dot"></i>  Rennes(FRANCE)



LANGUAGES {#contact}
--------------------------------------------------------------------------------

- French : native language
- English :  Level B2



INFORMATION TECHNOLOGY {#skills}
--------------------------------------------------------------------------------

- Experienced in statistical analysis, statistical learning models, and optimization methods.

- Proficient in Python (Scikit-Learn), R(Tidyverse), SQL, SAS, VBA,Bash, LateX, C++(basic level), 




HOBBIES {#skills}
--------------------------------------------------------------------------------

- Travelling (4 country)
- Enjoy participating in football, running, handball, and boxing.

----------------------------------------------------------------------------------

<footer>
- This resume was made with the R package  [**pagedown**](https://github.com/rstudio/pagedown).
</footer>


Main
================================================================================

Jumbong Junior {#title}
--------------------------------------------------------------------------------

### Looking for a 6-month end-of-study internship in Financial Engineering.


Education {data-icon=graduation-cap data-concise=true}
--------------------------------------------------------------------------------

### NATIONAL SCHOOL FOR STATISTICS AND DATA ANALYSIS (ENSAI)

RISK MANAGEMENT

Rennes, France

2022 - 2024

Master's in an engineering school focused on statistical courses (Machine Learning, time series) and programming (Python,R,SQL). Specialized in the final year in Risk Management and Financial Engineering, covering topics like banking risks and scoring methods.

### NATIONAL SCHOOL FOR STATISTICS AND ECONOMIC's ANALYSIS (ENSAE)

Engineering in Statistics and Economics

Dakar, Sénégal

2020 - 2021

Completed the first year of a Master's program in Economic Engineering, with coursework in Econometrics, Statistics, Programming, Macroeconomics, and Game Theory.

### UNIVERSITY OF YAOUNDE I

Mathematics 

Yaoundé , Cameroun

2017 - 2020

Earned a Bachelor's degree with a focus on mathematics courses, including Numerical Analysis (utilizing Python and MATLAB), Statistics, Probabilities, and Algebra.


Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### DATA ANALYST | HSBC

FINAL YEAR PROJECT

ENSAI, Rennes

Nov 2023 - on going


- Analysis of the sensitivity of financial data, such as credit spreads, in relation to climate metrics like carbon emissions.
- Study of the distribution of climate variables across sovereign debts.
- Potential analysis based on different climate scenarios proposed by the NGFS (Network for Greening the Financial Services).

### TIME SERIES 

ENERGY CONSUMPTION FORECASTING

ENSAI, Rennes

Nov 2023 - Dec 2023

- Analyzed historical energy consumption data and developed a forecasting model for future energy demand. 

###  RESEARCH ASSISTANT

[INRIA](https://www.inria.fr/fr/sistm)  : SISTM's TEAM

Bordeaux , France

Aug 2023 - Sep 2023

- Performed computational biology research  to understand the immune response to the Ebola vaccine.  
- Discovered significant impacts of age, gender, country, and laboratory variables on immune response variability.

### RESEARCH ASSISTANT

GEORGES POMPIDOU EUROPEAN HOSPITAL

Paris, France

Feb 2023 -  Sep 2023


- Carried out computational biology research to investigate the impact of capillary leakage on mortality rates (Logistic Regression and Generalized Mixed effect Regression).
- Managed data using the [MIMIC-IV](https://physionet.org/content/mimiciv/0.4/) database with SQL.



```{js move_disclaim, echo=FALSE}
(function() {
    var pages 
    var timer = 0;
    var changeDC = setInterval(function() {
        pages = document.querySelectorAll('.pagedjs_page');
        if(pages.length !== 2 && timer <= 5000) {
            timer += 200;
            return;
        }
        if(pages.length !== 2 && timer > 5000) return clearInterval(changeDC);
        var firstPage = pages[0];
        var lastePage = pages[pages.length - 1];
        var aside = firstPage.querySelector('#aside');
        var asideClone = aside.cloneNode();
        asideClone.id = "aside_last";
        var disclaim = document.querySelector('#disclaimer');
        asideClone.appendChild(disclaim);
        lastePage.querySelector('.pagedjs_page_content > div').appendChild(asideClone);
        clearInterval(changeDC);
    }, 200);
})()
```

